apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        imagePullPolicy: IfNotPresent
        image: docker.io/106734/authapi:latest
        ports:
          - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
  - name: static
    protocol: TCP
    port: 80
    targetPort: 80