apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
spec:
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat
        imagePullPolicy: IfNotPresent
        image: docker.io/106734/chatapi:latest
        ports:
          - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: chat
spec:
  selector:
    app: chat
  ports:
  - name: static
    protocol: TCP
    port: 80
    targetPort: 80